export const leaders = [
  {
    id: 1,
    year: "2023 - Present",
    name: "Prof. Olise",
    image: "/avatar.jpg",
    content: "Established the new AI research wing and secured $2M in department funding for sustainable technology.",
  },
  {
    id: 2,
    year: "2021 - 2023",
    name: "Prof. Jane Doe",
    image: "/cat.jpg",
    content: "Pioneered the remote learning transition and expanded the department curriculum to include cloud computing.",
  },
  {
    id: 3,
    year: "2018 - 2021",
    name: "Dr. Alice Johnson",
    image: "/cat.jpg",
    content: "Led the development of the cybersecurity program and implemented industry partnerships.",
  },
  {
    id: 4,
    year: "2015 - 2018",
    name: "Prof. Bob Smith",
    image: "/cat.jpg",
    content: "Introduced data science courses and collaborated on international research projects.",
  },
  {
    id: 5,
    year: "2012 - 2015",
    name: "Dr. Carol Williams",
    image: "/cat.jpg",
    content: "Focused on student mentorship and increased graduation rates by 15%.",
  },
  {
    id: 6,
    year: "2009 - 2012",
    name: "Prof. David Brown",
    image: "/cat.jpg",
    content: "Established the entrepreneurship incubator and secured patents for department innovations.",
  },
  {
    id: 7,
    year: "2006 - 2009",
    name: "Dr. Emma Davis",
    image: "/cat.jpg",
    content: "Promoted diversity initiatives and expanded access to underrepresented groups.",
  },
  {
    id: 8,
    year: "2003 - 2006",
    name: "Prof. Frank Garcia",
    image: "/cat.jpg",
    content: "Directed the AI ethics committee and published key papers on responsible AI.",
  },
  {
    id: 9,
    year: "2000 - 2003",
    name: "Dr. Grace Lee",
    image: "/cat.jpg",
    content: "Managed the department's digital transformation and integrated new technologies.",
  },
  {
    id: 10,
    year: "1997 - 2000",
    name: "Prof. Henry Miller",
    image: "/cat.jpg",
    content: "Launched the alumni network and increased funding through donations.",
  },
];